import numpy as np

class QuadcopterSimulation:
    def __init__(self):
        # 1. Physical Parameters
        self.mass = 1.0        # kg
        self.gravity = 9.81    # m/s^2
        self.d = 0.25          # distance from center to motor (meters)
        self.kf = 1e-5         # thrust coefficient
        self.km = 1.5e-6       # torque coefficient
        
        # New: Moment of Inertia (kg*m^2)
        self.Ixx = 0.01  
        self.Iyy = 0.01  
        self.Izz = 0.02  
        
        # 2. State Variables
        self.z = 0.0           
        self.z_dot = 0.0    
        # New: X and Y Translation States
        self.x = 0.0
        self.x_dot = 0.0
        self.y = 0.0
        self.y_dot = 0.0   
        
        # New: Angular States (Angle and Angular Velocity in radians)
        self.phi = 0.0         # Roll
        self.phi_dot = 0.0
        self.theta = 0.0       # Pitch
        self.theta_dot = 0.0
        self.psi = 0.0         # Yaw
        self.psi_dot = 0.0
        
        # 3. The Control Allocation Matrix
        self.allocation_matrix = np.array([
            [self.kf, self.kf, self.kf, self.kf],
            [-self.d * self.kf, self.d * self.kf, self.d * self.kf, -self.d * self.kf],
            [-self.d * self.kf, -self.d * self.kf, self.d * self.kf, self.d * self.kf],
            [-self.km, self.km, -self.km, self.km]
        ])
        
        self.inv_allocation_matrix = np.linalg.inv(self.allocation_matrix)

    def mixer(self, thrust, tau_roll, tau_pitch, tau_yaw):
        desired_forces = np.array([thrust, tau_roll, tau_pitch, tau_yaw])
        omegas_squared = np.dot(self.inv_allocation_matrix, desired_forces)
        omegas_squared = np.clip(omegas_squared, 0, None)
        return np.sqrt(omegas_squared)

    def step(self, omegas, dt):
        omegas_squared = omegas**2
        
        # --- Z-Axis Translation ---
        total_thrust = self.kf * np.sum(omegas_squared)
        
        # We multiply by cos(phi) * cos(theta) because if the drone is tilted, 
        # not all thrust is pointing perfectly up against gravity.
        upward_thrust = total_thrust * np.cos(self.phi) * np.cos(self.theta)
        net_force_z = upward_thrust - (self.mass * self.gravity)
        
        self.z_dot += (net_force_z / self.mass) * dt
        self.z += self.z_dot * dt

        # --- X and Y Translation ---
        # The horizontal components of the thrust vector
        net_force_x = total_thrust * np.sin(self.theta) * np.cos(self.phi)
        net_force_y = -total_thrust * np.sin(self.phi)
        
        # Integrate X
        self.x_dot += (net_force_x / self.mass) * dt
        self.x += self.x_dot * dt
        
        # Integrate Y
        self.y_dot += (net_force_y / self.mass) * dt
        self.y += self.y_dot * dt
        
        if self.z < 0.0:
            self.z = 0.0
            self.z_dot = 0.0

        # --- Angular Rotation ---
        # 1. Calculate Torques generated by the current motor speeds
        tau_phi = self.d * self.kf * (omegas_squared[1] + omegas_squared[2] - omegas_squared[0] - omegas_squared[3])
        tau_theta = self.d * self.kf * (omegas_squared[2] + omegas_squared[3] - omegas_squared[0] - omegas_squared[1])
        tau_psi = self.km * (omegas_squared[1] + omegas_squared[3] - omegas_squared[0] - omegas_squared[2])

        # 2. Calculate Angular Acceleration (Torque / Inertia)
        phi_ddot = tau_phi / self.Ixx
        theta_ddot = tau_theta / self.Iyy
        psi_ddot = tau_psi / self.Izz

        # 3. Integrate to get Angular Velocity
        self.phi_dot += phi_ddot * dt
        self.theta_dot += theta_ddot * dt
        self.psi_dot += psi_ddot * dt

        # 4. Integrate to get Angle
        self.phi += self.phi_dot * dt
        self.theta += self.theta_dot * dt
        self.psi += self.psi_dot * dt

class PIDController:
    # 1. Add min_output to the initialization
    def __init__(self, kp, ki, kd, min_output, max_output):
        self.kp = kp
        self.ki = ki
        self.kd = kd
        
        self.previous_error = 0.0
        self.integral = 0.0
        
        self.min_output = min_output 
        self.max_output = max_output 

    def compute(self, setpoint, current_value, dt):
        error = setpoint - current_value
        P = self.kp * error
        
        self.integral += error * dt
        self.integral = np.clip(self.integral, -10, 10) 
        I = self.ki * self.integral
        
        D = self.kd * (error - self.previous_error) / dt
        self.previous_error = error
        
        output = P + I + D
        
        # 2. Clip using both min and max bounds
        return np.clip(output, self.min_output, self.max_output)

import matplotlib.pyplot as plt

sim = QuadcopterSimulation()

# --- OUTER LOOP PIDs (Position Controllers) ---
# These look at position error (meters) and output desired acceleration (m/s^2)
# Max acceleration is limited to 5 m/s^2 to prevent overly aggressive maneuvers
x_pid = PIDController(kp=1.2, ki=0.0, kd=2.0, min_output=-5.0, max_output=5.0)
y_pid = PIDController(kp=1.2, ki=0.0, kd=2.0, min_output=-5.0, max_output=5.0) # NOTE: ALL Ki's are set to ZERO because this is a frictionless MATHEMATICAL MODEL
z_pid = PIDController(kp=7.8, ki=0.0, kd=5.7, min_output=-5.0, max_output=5.0)

# --- INNER LOOP PIDs (Attitude Controllers) ---
# These look at angle error (radians) and output desired torque
roll_pid = PIDController(kp=3.0, ki=0.0, kd=0.8, min_output=-0.5, max_output=0.5)
pitch_pid = PIDController(kp=3.0, ki=0.0, kd=0.8, min_output=-0.5, max_output=0.5)
yaw_pid = PIDController(kp=1.0, ki=0.0, kd=0.5, min_output=-0.5, max_output=0.5)

dt = 0.01
duration = 15.0
time_steps = int(duration / dt)

# Let's set a 3D waypoint
target_x = 10.0
target_y = 5.0
target_z = 5.0

time_log = np.linspace(0, duration, time_steps)
x_log = np.zeros(time_steps)
y_log = np.zeros(time_steps)
z_log = np.zeros(time_steps)

for i in range(time_steps):
    # 1. OUTER LOOP: Get required accelerations
    ax_req = x_pid.compute(target_x, sim.x, dt)
    ay_req = y_pid.compute(target_y, sim.y, dt)
    az_req = z_pid.compute(target_z, sim.z, dt)
    
    # 2. VECTOR MATH: Convert accelerations to Thrust and Angles
    # Add gravity to the requested Z acceleration
    total_accel = np.sqrt(ax_req**2 + ay_req**2 + (az_req + sim.gravity)**2)
    
    # F = ma
    desired_thrust = sim.mass * total_accel
    
    # Calculate angles using inverse trigonometry. 
    # We clip the argument between -1 and 1 to prevent math errors.
    pitch_arg = np.clip(ax_req / total_accel, -1.0, 1.0)
    target_pitch = np.arcsin(pitch_arg)
    
    roll_arg = np.clip(-ay_req / total_accel, -1.0, 1.0)
    target_roll = np.arcsin(roll_arg)
    
    target_yaw = 0.0 # Keeping yaw fixed at 0 for now
    
    # 3. INNER LOOP: Get desired torques to reach target angles
    desired_tau_roll = roll_pid.compute(target_roll, sim.phi, dt)
    desired_tau_pitch = pitch_pid.compute(target_pitch, sim.theta, dt)
    desired_tau_yaw = yaw_pid.compute(target_yaw, sim.psi, dt)
    
    # 4. MIXER & PHYSICS
    omegas = sim.mixer(desired_thrust, desired_tau_roll, desired_tau_pitch, desired_tau_yaw)
    sim.step(omegas, dt)
    
    x_log[i] = sim.x
    y_log[i] = sim.y
    z_log[i] = sim.z

# Plotting the 3D Trajectory in 2D graphs
plt.figure(figsize=(15, 4))

plt.subplot(1, 3, 1)
plt.plot(time_log, x_log, color='red')
plt.axhline(y=target_x, color='black', linestyle='--')
plt.title('X Position (Forward)')

plt.subplot(1, 3, 2)
plt.plot(time_log, y_log, color='green')
plt.axhline(y=target_y, color='black', linestyle='--')
plt.title('Y Position (Lateral)')

plt.subplot(1, 3, 3)
plt.plot(time_log, z_log, color='blue')
plt.axhline(y=target_z, color='black', linestyle='--')
plt.title('Z Position (Altitude)')

plt.tight_layout()
plt.show()